{{- if and (not .Values.steam.apiKeySecret.name) .Values.steam.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tourney-controller.steamSecretName" . }}
  labels:
{{ include "tourney-controller.labels" . | indent 4 }}
type: Opaque
data:
  api-key: {{ .Values.steam.apiKey | b64enc | quote }}
{{- end }}