{{- if and (not .Values.database.existingSecret.name) .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tourney-controller.dbSecretName" . }}
  labels:
{{ include "tourney-controller.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | b64enc | quote }}
{{- end }}
